mtp:
  consumption:
    cluster.nodeName: nodeConsumption0
    akka:
      akkaSystemName: MtpConsumption
      logConfiguration: false
      logClusterMetrics: false
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: mtp
    balancingPool.instances: 5
    kafkaClient:
      bootstrapServers: localhost:9092
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      batchSize: 100
      topicName: mtp.transaction
      reconnectBackoffMs: 100
    httpServer:
      bindHost: localhost
      bindPort: 9090
      publicProtocol: http
      publicHost: localhost
      publicPort: 9090

