mtp:
  core:
    cluster.nodeName: nodeClient0
    akka:
      akkaSystemName: MtpClient
      logConfiguration: false
      logClusterMetrics: false
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: mtp
