mtp:
  processor:
    cluster:
      appName: MtpProcessor
      nodeName: nodeProcessor0
    akka:
      akkaSystemName: MtpProcessor
      logConfiguration: false
      logClusterMetrics: false
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: mtp
    spark:
      master: local[10]
      cassandraHosts: localhost
      cleanerTtl: 7200
      batchInterval: 10000
      checkpointDir: /tmp/spark-processor
    kafkaServer:
      groupId: mtp.group
      host: localhost
      port: 9092
      advertisedHost: localhost
      advertisedPort: 9092
      topic:
        name: mtp.transaction
        numPartitions: 1
        replicationFactor: 1
    zookeeper:
      connect: localhost:2181

#      hosts: localhost
#      ingest-rate: 1s
#      partitioner:
#        fqcn: kafka.producer.DefaultPartitioner
#      encoder:
#        fqcn: kafka.serializer.StringEncoder
#      decoder:
#        fqcn: kafka.serializer.StringDecoder
#      batch:
#        send:
#          size: 100
