spring:
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
security:
    basic:
        enabled: false
server:
  port: 8080
mtp:
  frontend:
    cluster:
      appName: MtpFrontend
      nodeName: nodeFrontend0
    akka:
      akkaSystemName: MtpFrontend
      logConfiguration: false
      logClusterMetrics: false
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: mtp
    spark:
      master: local[10]
      cassandraHosts: localhost
      cleanerTtl: 7200
      batchInterval: 10000
      checkpointDir: /tmp/spark-frontend
    security:
        authentication:
            oauth:
                clientid: mtpapp
                secret: mySecretOAuthSecret
                # Token is valid 30 minutes
                tokenValidityInSeconds: 1800
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 5b802eb2cabc806b60315220f1aac2948a834541
    swagger:
        title: MTP API
        description: MTP API documentation
        version: 0.3.0
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl: