
mtp:

  core:
    cluster:
      nodeName: nodeProcessor0
    akka:
      configurationName: MtpProcessor
      logConfiguration: false
      logClusterMetrics: false
    cassandra:
      contactPoints: localhost
      port: 9042
      keyspace: mtp

  processor:
    spark:
      master: local[10]
      cassandra:
        hosts: localhost
      cleaner:
        ttl: 7200
      batch:
        interval: 10000
      checkpoint:
        dir: /tmp
    kafka:
      group.id: mtp.group
      host.name: localhost
      port: 9092
      topic:
        name: mtp.transaction
        numPartitions: 1
        replicationFactor: 1
    zookeeper:
      connect: localhost:2181

#      hosts: localhost
#      ingest-rate: 1s
#      partitioner:
#        fqcn: kafka.producer.DefaultPartitioner
#      encoder:
#        fqcn: kafka.serializer.StringEncoder
#      decoder:
#        fqcn: kafka.serializer.StringDecoder
#      batch:
#        send:
#          size: 100
